# Generated by Django 4.0 on 2026-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deskripsi', models.CharField(max_length=100)),
                ('Kategori', models.TextField()),
            ],
        ),
    ]
