# Generated by Django 4.0 on 2026-05-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='Deskripsi',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='Kategori',
            new_name='kategori',
        ),
    ]
